name = "backups"
name_pretty = "Backups"
fixed_order = true
icon = ""

[[entries]]
icon = ""
text = "Archive files"
actions = { "backup-files" = "ghostty --class=local.floating -e backup-files" }

[[entries]]
icon = ""
text = "Unpack archive"
actions = { "backup-restore" = "ghostty --class=local.floating -e backup-restore" }
