###############
### SOURCES ###
###############
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/environments.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/layerrules.conf
source = ~/.config/dotfiles/current/theme/hyprland.conf
