# Background and foreground colors
background = #0d2020
foreground = #c2c7c7

# Standard colors
palette = 0=#0d2020
palette = 1=#7C8271
palette = 2=#968C72
palette = 3=#DE9958
palette = 4=#B0AB90
palette = 5=#C8B999
palette = 6=#BDC2A9
palette = 7=#c2c7c7

# Bright colors
palette = 8=#5d7171
palette = 9=#7C8271
palette = 10=#968C72
palette = 11=#DE9958
palette = 12=#B0AB90
palette = 13=#C8B999
palette = 14=#BDC2A9
palette = 15=#c2c7c7
