# Background and foreground colors
background = #0f0914
foreground = #f5dbab

# Standard colors
palette = 0=#0f0914
palette = 1=#8F4756
palette = 2=#AD5158
palette = 3=#E05F55
palette = 4=#F89236
palette = 5=#FB9258
palette = 6=#FCB053
palette = 7=#f5dbab

# Bright colors
palette = 8=#ab9977
palette = 9=#8F4756
palette = 10=#AD5158
palette = 11=#E05F55
palette = 12=#F89236
palette = 13=#FB9258
palette = 14=#FCB053
palette = 15=#f5dbab
