# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.


general {
    col.active_border = rgba(C8B99944) rgba(BDC2A944) 45deg
    col.inactive_border = rgba(0d202088)
}
